# Generated by Django 3.0.3 on 2020-04-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('text', models.CharField(max_length=500)),
                ('sentat', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
